Course Timetabling: Database Save  - fixed the NoClassDefFoundError (introduced in revision 4596) as remote solver servers do not have the Spring dependencies